#!/bin/bash
set -euo pipefail

CREDS_FILE=$(mktemp)
trap "rm -f $CREDS_FILE" EXIT
cat > $CREDS_FILE <<EOF
{
  "oauth2": {
    "client_id":"$2",
    "client_secret":"$3",
    "server":"https://auth-plus.gw.prod01.advancedtelematic.com"
  },
  "ostree":{
    "server":"https://treehub.gw.prod01.advancedtelematic.com"
  }
}
EOF
$1 --ref master --repo sota_tools/repo --credentials $CREDS_FILE -n
