#!/bin/bash
set -eu

TEMP_DIR=$(mktemp -d)

PORT=$(python -c 'import socket; s=socket.socket(); s.bind(("", 0)); print(s.getsockname()[1]); s.close()')
TREEHUB="{\
  \"ostree\": {\
    \"server\": \"http://localhost:$PORT/\"\
  }\
}"

TREEHUB_DEST="{\
  \"ostree\": {\
    \"server\": \"http://localhost:1/\"\
  }\
}"

echo $TREEHUB > $TEMP_DIR/treehub.json
echo $TREEHUB_DEST > $TEMP_DIR/treehub_dest.json

./tests/sota_tools/treehub_server.py $PORT &
sleep 1

$1 --commit 16ef2f2629dc9263fdf3c0f032563a2d757623bbc11cf99df25c3c3f258dccbe -f $TEMP_DIR/treehub.json -p $TEMP_DIR/treehub_dest.json --name testname -h hwids
exit_code=$?
kill %1
exit $exit_code