#!/bin/bash
set -euo pipefail
trap 'kill %1' EXIT

TEMP_DIR=$(mktemp -d)

PORT=$(python -c 'import socket; s=socket.socket(); s.bind(("", 0)); print(s.getsockname()[1]); s.close()')
TREEHUB="{\
  \"ostree\": {\
    \"server\": \"http://localhost:$PORT/\"\
  }\
}"

echo $TREEHUB > $TEMP_DIR/treehub.json
./tests/sota_tools/treehub_server.py $PORT &
sleep 1

$1 --commit 7f9237e1048fa97b204a2c42028e03eec27d891b5dfab0589589a38987d76199 -f $TEMP_DIR/treehub.json -p $TEMP_DIR/treehub.json --name testname -h hwids -n
exit_code=$?
exit $exit_code