#!/bin/bash
set -eu
TARGET="Unable to read a-non-existent-file as archive or json file"
# File not found and invalid/corrupt files are treated the same
$1 --commit 7f9237e1048fa97b204a2c42028e03eec27d891b5dfab0589589a38987d76199 -f ./tests/sota_tools/auth_test_good.zip -p a-non-existent-file --name testname -h hwids 2>&1 | grep "$TARGET"
