excludes:
  paths:
  - pattern: "tests/**"
    reason: "TEST_TOOL_OF"
    comment: "This directory contains tests which are not distributed."
  - pattern: "third_party/googletest/**"
    reason: "TEST_TOOL_OF"
    comment: "This directory contains support code for tests which are not distributed."
  - pattern: "third_party/HdrHistogram_c/**"
    reason: "TEST_TOOL_OF"
    comment: "This directory contains support code for tests which are not distributed."
  - pattern: "third_party/junit/ctest2junit.xsl"
    reason: "TEST_TOOL_OF"
    comment: "This file contains support code for tests which are not distributed."
  - pattern: "thirdparty.spdx"
    reason: "TEST_TOOL_OF"
    comment: "This file contains metadata which are not distributed."

