FROM debian:testing
LABEL Description="Aktualizr testing dockerfile for Debian Unstable + static checks"

ENV DEBIAN_FRONTEND noninteractive

# for clang-format 3.8
RUN echo "deb http://ftp.de.debian.org/debian stable main" >> /etc/apt/sources.list
RUN echo "deb-src http://ftp.de.debian.org/debian stable main" >> /etc/apt/sources.list

# It is important to run these in the same RUN command, because otherwise
# Docker layer caching breaks us
RUN apt-get update && apt-get -y install \
  apt-transport-https \
  asn1c \
  autoconf \
  automake \
  bison \
  clang-6.0 \
  clang-tidy-6.0 \
  clang-tools-6.0 \
  clang-format-3.8 \
  cmake \
  curl \
  dpkg-dev \
  e2fslibs-dev \
  g++ \
  gcc \
  git \
  lcov \
  libarchive-dev \
  libboost-dev \
  libboost-log-dev \
  libboost-program-options-dev \
  libboost-random-dev \
  libboost-regex-dev \
  libboost-system-dev \
  libboost-test-dev \
  libboost-thread-dev \
  libcurl4-openssl-dev \
  libdpkg-dev \
  libengine-pkcs11-openssl \
  libexpat1-dev \
  libglib2.0-dev \
  libgpgme11-dev \
  libgtest-dev \
  liblzma-dev \
  libostree-dev \
  libp11-dev \
  libsodium-dev \
  libsqlite3-dev \
  libssl-dev \
  libsystemd-dev \
  libtool \
  make \
  opensc \
  ostree \
  pkg-config \
  psmisc \
  python3-dev \
  python3-gi \
  python3-openssl \
  python3-requests \
  python3-venv \
  softhsm2 \
  valgrind \
  wget

RUN ln -s clang-6.0 /usr/bin/clang && \
    ln -s clang++-6.0 /usr/bin/clang++

WORKDIR aktualizr
ADD . src
