FROM ubuntu:xenial
LABEL Description="Aktualizr deb package testing dockerfile"

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && apt-get -y install debian-archive-keyring
RUN apt-get update && apt-get install -y \
  libarchive13 \
  libc6 \
  libcurl3 \
  libgcc1 \
  libsodium18 \
  libsqlite3-0 \
  libssl1.0.0 \
  libstdc++6 \
  lshw \
  python3

ENTRYPOINT /persistent/test_aktualizr_deb_and_update.sh
