#ifndef AKTUALIZR_PARTIAL_UPTANE_CONFIG_H_
#define AKTUALIZR_PARTIAL_UPTANE_CONFIG_H_

#define CONFIG_UPTANE_MAX_SIGS 1
#define CONFIG_UPTANE_TARGETS_BUF_SIZE 256
#define CONFIG_UPTANE_NOMALLOC
#define CONFIG_UPTANE_SINGLETHREADED

#endif /*AKTUALIZR_PARTIAL_UPTANE_CONFIG_H_*/
