= Set up additional environments
ifdef::env-github[]

[NOTE]
====
We recommend that you link:https://docs.ota.here.com/ota-client/latest/{docname}.html[view this article in our documentation portal]. Not all of our articles render correctly in GitHub.
====
endif::[]


An environment is your working space in your https://connect.ota.here.com[OTA Connect account], where you can create and manage software update projects.

If you do not want to mix up test and production software xref:evaluation-to-prod.adoc#_integrate_ota_connect[during integration with OTA Connect], you may create additional environments. You can xref:ota-web::create-environment.adoc[create] up to 10 additional environments in one https://connect.ota.here.com[OTA Connect account].

For example, you may need to have different environments for development, QA, and production.

IMPORTANT: The limit of 10 additional environments applies even if you leave the environments that you have created. There is currently no way to delete environments.

== Additional environments

To manage the different stages of production workflow, you can create additional environments for the following:

* A developer user such as _\dev@acme.com_
* A QA user such as _\qa@acme.com_
* A production user such as _\prod@acme.com_

These environments provide you with a convenient way to separate your development, QA, and production resources.


After you create an environment, you can xref:ota-web::manage-members.adoc[add] your colleagues to work together on device provisioning, device groups, software versions, software updates, and campaigns.

To get more information on the *Environments* feature, see the xref:ota-web::environments-intro.adoc[Environments] section in the OTA Connect User Guide.
