    = Add/remove a targets key and set the threshold

== Adding a targets key

Follow these steps to create a new key that can be used to sign targets.json.

. Generate a new key:
+
----
garage-sign key generate --name my-key --type rsa --repo my-repo
----
. Add the generated key to a list of keys allowed to sign targets.json:
+
----
garage-sign root targets-key add --key-name my-key --repo my-repo
----
. Sign root.json and push it to the server:
+
----
garage-sign root sign --key-name root-key --repo my-repo
garage-sign root push --repo my-repo
----

Now the new key can be used to sign targets.json.

== Setting the threshold for targets.json

To set the minimum number of keys required to sign targets.json, execute the following commands (in this example the threshold is set to 2):

. Set new threshold for targets.json
+
----
garage-sign targets set-threshold --threshold 2 --repo my-repo
----
This will update the threshold value in root.json.
. Sign root.json and push it to the server:
+
----
garage-sign root sign --key-name root-key --repo my-repo
garage-sign root push --repo my-repo
----

Now for targets.json to be valid it must be signed with at least two keys, e.g.:
----
garage-sign targets sign --key-name key1 --key-name key2 --repo my-repo
----
If targets.json was signed with a number of keys which is less than the threshold, the 'Invalid offline targets' error will be shown when trying to push targets.json to the server.

== Removing a targets key

. To remove a targets key, run the following commands:
+
----
garage-sign root targets-key remove --key-name my-key --repo my-repo
----
. Sign root.json and push it to the server:
+
----
garage-sign root sign --key-name root-key --repo my-repo
garage-sign root push --repo my-repo
----

The key has been removed from root.json and cannot be used anymore.