= BSP Integration
ifdef::env-github[]

[NOTE]
====
We recommend that you link:https://docs.ota.here.com/ota-client/latest/{docname}.html[view this article in our documentation portal]. Not all of our articles render correctly in GitHub.
====
endif::[]


Adding support for a new board isn't too hard, if you're already familiar with Yocto and you have good documentation about your board's hardware. In this guide, we'll present conceptual information on what steps need to be taken, and then illustrate the concrete steps needed by taking an NXP board (the https://www.nxp.com/design/qoriq-developer-resources/qoriq-ls1043a-development-board:LS1043A-RDB[LS1043A-RDB]) as an example.

All of the changes we're making in this guide will be done in https://github.com/advancedtelematic/meta-updater/[meta-updater]. While you're working on adding support for your new board, you should fork meta-updater. Once the support is ready, please feel free to make a pull request to get it merged into mainline meta-updater.

NOTE: You can also add support for your board by writing a separate layer--see https://github.com/advancedtelematic/meta-updater-raspberrypi[meta-updater-raspberrypi] for an example of this approach.



== Key Concepts

There are two important concepts about *OSTree* and *meta-updater* that you need to know before proceeding with the integration.

. *OSTree*
+
OSTree image deployments are installed inside the `/ostree` directory, and then hard-linked into place in `/boot` at boot time using a bootloader configuration script generated by OSTree when the image is verified.
+
On an OSTree-managed system, OSTree can tell the bootloader which kernel, initramfs, and device tree blob to load. There are two basic ways to do this:
+
* On a system with link:https://source.denx.de/u-boot/u-boot/raw/master/doc/develop/distro.rst[Distro Boot], OSTree sets the U-Boot environment variables to the appropriate values when OSTree switches to a new deployment.
* Systems that do not support Distro Boot (for example, GRUB) have a very minimal, simple bootloader configuration script that is fixed in the bootloader partition. This script points the bootloader to a second bootloader script, which is managed by OSTree. OSTree switches to a new deployment by replacing the second script with a new one which points to the new deployment.
+
NOTE: OSTree will only switch to the new deployment once it has verified that the complete filesystem tree is present; libaktualizr will only instruct OSTree to switch once it has performed xref:uptane.adoc[Uptane] verification on the metadata directing it to switch.
. *meta-updater*
+
The https://github.com/advancedtelematic/meta-updater/[meta-updater] layer contains recipes for the applications and libraries required by libaktualizr and OSTree, along with patches to upstream recipes when modifications are necessary. It also includes board and image classes for the OTA-specific needs of the boards it supports.


== Steps in adding a new board

These are the required steps you need to integrate an unsupported board with OTA Connect.

. xref:add-board-class.adoc[Add a board class for the new target board in meta-updater]
. xref:setup-boot-image-for-ostree.adoc[Set up a boot image layout for OSTree compatibility]
. xref:add-meta-updater-to-vendors-sdk.adoc[Add meta-updater features to the vendor's SDK]




