= BSP Integration
ifdef::env-github[]

[NOTE]
====
We recommend that you link:https://docs.ota.here.com/ota-client/latest/{docname}.html[view this article in our documentation portal]. Not all of our articles render correctly in GitHub.
====
endif::[]


The list of boards currently supported by HERE OTA Connect can be seen xref:supported-boards.adoc[here].
If your board isn't yet supported, we can show you how to add xref:ostree-and-treehub.adoc[OSTree] support to a https://www.yoctoproject.org/docs/2.7/bsp-guide/bsp-guide.html[Yocto BSP] via the meta-updater layer. This is a pre-condition for using OTA Connect’s built-in support for the OSTree image type on a new board and enables efficient deltas for Linux-based embedded devices.


== Key Concepts

There are two important concepts about *OSTree* and the *meta-updater* that you need to know before proceeding with the integration.

. *OSTree*

OSTree image deployments are installed inside the `/ostree directory`, and then hard-linked into place in `/boot` at boot time using a bootloader configuration script generated by OSTree when the image is verified.

On an OSTree-managed system, OSTree can tell the bootloader which kernel initramfs and device tree blob to load. There are two basic ways to do this:

* on a system with link:https://gitlab.denx.de/u-boot/u-boot/raw/master/doc/README.distro[distroboot], OSTree sets u-boot environment variables to the appropriate values when it switches to a new deployment.
* In systems that don’t support distroboot (e.g. GRUB) there will be a very minimal, simple bootloader configuration script that is fixed in the bootloader’s partition. The minimal script then points the bootloader to a second, "real" bootloader script, which is managed by OSTree. The way OSTree switches to a new deployment is by replacing the second script so that it points to the new deployment.


NOTE: OSTree will only switch to the new development once it has verified that the complete filesystem tree is present; libaktualizr will only instruct OSTree to switch once it has performed xref:uptane.adoc[Uptane] verification on the metadata directing it to switch.


[start=2]
. *meta-updater*

The https://github.com/advancedtelematic/meta-updater/[meta-updater] in the Yocto layer contains recipes for the applications and libraries required by libaktualizr and OSTree, along with patches to upstream recipes when modifications are necessary. It also includes board and image classes for the OTA-specific needs of the boards it supports.


== Required steps in adding a new board

These are our recommended steps to integrate an unsupported board with OTA Connect.

. xref:add-board-class.adoc[Add a board class for the new target board in meta-updater]
. xref:setup-boot-image-for-ostree.adoc[Set up a boot image layout for OSTree compatibility]
. xref:add-meta-updater-to-vendors-sdk.adoc[Add meta-updater features to the vendor's SDK]




