= Add custom metadata fields to targets metadata
ifdef::env-github[]

[NOTE]
====
We recommend that you link:https://docs.ota.here.com/ota-client/latest/{docname}.html[view this article in our documentation portal]. Not all of our articles render correctly in GitHub.
====
endif::[]





The Uptane metadata we advised you to xref:rotating-signing-keys.adoc[rotate offline], are the `root.json` and `targets.json` metadata files in the *image repository*. For more information on these metadata files please refer to xref:uptane.adoc#_uptane_metadata[Uptane metadata overview]. The `targets.json` metadata file for the image repository can be edited. It has a `custom` field that can be edited to suit your needs or requirements. Below are a few examples of scenarios where you might want to edit the `targets.json` file.



== Possible Use Cases to customize `targets.json`

A few cases might occur where you will have to edit the `custom` field within the `targets.json` file. These might include:

* to provide installation instructions or scripts for an ECU
* to add extra tracking fields for internal compliance or auditing
* to provide unlock codes
* to add material for configuration
* to add an extra notice or text to be displayed for your users


[NOTE]
====
For more information on additional use cases which will require customization of the `targets` metadata file, please refer to the section https://uptane.github.io/papers/ieee-isto-6100.1.0.0.uptane-standard.html#rfc.section.5.2.3.1.1['Custom metadata about images' in the Uptane standard].
====



== Steps in updating `targets.json` metadata

. Before editing the `targets.json` metadata file, make sure you already have your new offline `root` and `targets` keys, generated and signed by the old keys. To generate and rotate the new Uptane keys for `root` and `targets` metadata please refer to xref:rotating-signing-keys.adoc#_rotate_the_keys_for_root_and_targets_metadata[managing keys for software metadata].
. With your new `root` and `targets` keys generated, open the `targets.json` metadata file and navigate to the `custom` field. An example of the `custom` field is shown below:
+
----
"custom": {
  "name": "aegisub-font",
  "version": "1",
  "hardwareIds": [
    "kmk-docker-debian"
  ],
  "targetFormat": null,
  "uri": null,
  "createdAt": "2018-08-20T09:28:27Z",
  "updatedAt": "2018-08-20T09:28:27Z"
}
----

[start=3]
. Maintain the default values specified, however you can add any extra values you want within this `custom` field as in the example below:
+
----
"custom": {
  "name": "aegisub-font",
  "display": "ecu-software-1",
  "description": "",
  "author": "adam123",
  "reference": "https://docs.ota.here.com/ota-client/latest/rotating-signing-keys.html",
  "version": "1",
  "hardwareIds": [
    "kmk-docker-debian"
  ],
  "targetFormat": null,
  "uri": null,
  "createdAt": "2018-08-20T09:28:27Z",
  "updatedAt": "2018-08-20T09:28:27Z"
}
----

[start=4]
. After editing the `targets.json` metadata file, you need to sign the new metadata file with your offline `targets` key.
+
----
garage-sign targets sign --repo myimagerepo --key-name mytargets
----
+
. Afterwards, upload the newly signed `targets.json` to OTA Connect with the command below:
+
----
garage-sign targets push --repo myimagerepo
----

+
IMPORTANT: Each time the `targets.json` file is edited, it must be signed by your offline `targets` key, and then uploaded to OTA Connect.

+
NOTE: You also might want to add custom metadata while bitbaking. You can do this, for example, by modifying the `IMAGE_CMD_garagesign` function in link:https://github.com/advancedtelematic/meta-updater/blob/master/classes/image_types_ostree.bbclass#L217[image_types_ostree.bbclass]. A detailed guide on how to accomplish this is out of our scope, however. Refer to http://www.yoctoproject.org/docs/2.7/dev-manual/dev-manual.html[the Yocto Reference Manual] for further details.

