= Text Device-credential Provisioning
ifdef::env-github[]

[NOTE]
====
We recommend that you link:https://docs.ota.here.com/ota-client/latest/{docname}.html[view this article in our documentation portal]. Not all of our articles render correctly in GitHub.
====
endif::[]


Although shared-credential provisioning is useful for evaluating OTA Connect, we don't recommend that you use it in production.

If you want to test provisioning properly, you should provision devices with their own certificates. In a production scenario, you'll need to automate the process of provisioning devices with their own certificates, but for testing you can provision devices manually.

The following major steps show you how to provision test devices with device certificates:

* xref:generate-selfsigned-root.adoc[Generate a test root certificate].
+
If you don't yet have your fleet's root certificate, we show you how to generate one yourself for testing.

* xref:provide-testroot-cert.adoc[Provide us with your test root certificate]
+
We'll need to register your test root certificate with a test account, so that the OTA Connect server can verify your test device certificates.

* xref:generatetest-devicecert.adoc[Generate and sign a test device certificate]
+
Once you've generated a test root certificate, you can use it to sign a test device certificate.

* xref:enable-device-cred-provtest.adoc[Enable and install the device certificate]
+
We show you how to enable device-credential provisioning and install a device certificate on a test device. Once you've provisioned test devices with certificates, they can authenticate with the OTA Connect server.