= Set Up Device Provisioning
ifdef::env-github[]

[NOTE]
====
We recommend that you link:https://docs.ota.here.com/ota-client/latest/{docname}.html[view this article in our documentation portal]. Not all of our articles render correctly in GitHub.
====
endif::[]


In this section, you'll learn how provisioning in production is different from the provisioning method that you used to get started. You'll also understand the major steps involved in provisioning devices for production.

== Why is there a different provisioning method for production?

include::partial$why-different-prov-methods.adoc[]

== How to provision with device credentials

include::partial$how-prov-with-device-cred.adoc[]

*To set up your environment for device credential provisioning, you need to perform the following major steps:*


* *xref:provide-root-cert.adoc[Provide us with the root certificate for your fleet]*
+
We'll need to register this certificate for your account so that OTA Connect can validate your device certificates.
* *xref:enable-device-cred-provisioning.adoc[Install your device certificates on devices]*
+
The installation process happens outside of OTA Connect but we can give you some pointers on how to set up this process.
* *xref:enable-device-cred-provisioning.adoc[Configure the OTA Connect client to use your device certificates for provisioning]*
+
We show you how to do this with or without an HSM.
