= Enable device-credential provisioning and install device certificate
ifdef::env-github[]

[NOTE]
====
We recommend that you link:https://docs.ota.here.com/ota-client/latest/{docname}.html[view this article in our documentation portal]. Not all of our articles render correctly in GitHub.
====
endif::[]


//MC: This is a copy of the topic "enable-device-cred-provisioning.adoc" but intended for the "test" use case. Need to use more includes to reduce redundancy.

If you've followed our recommendation to use device-credential provisioning, you'll need to test how it works in your environment. You start by building disk images that are configured to use device-credential provisioning.

After you have flashed those images to devices, you boot the image and install the device certicate for each device. You can install the certificate to the device's fileystem or use an HSM.

== Enable and install _without_ an HSM

You don't need an HSM to provision with device credentials, but we recommend that you use one. If you want to do without an HSM for now, use this procedure.

To enable device-credential provisioning and install device certificates _without_ an HSM, follow these steps: ::

. Add the following lines to your `conf/local.conf`:
+
----
SOTA_CLIENT_PROV = "aktualizr-device-prov"
SOTA_DEPLOY_CREDENTIALS = "0"
SOTA_PACKED_CREDENTIALS = "/path/to/your/credentials.zip"
IMAGE_INSTALL_append = " dropbear "
----
+
[NOTE]
====
The line `IMAGE_INSTALL_append = " dropbear "` ensures that an ssh server is installed on the image. You'll need to ssh into the device to copy the certificates to the device's filesystem.
====
. Build a standard image using bitbake.
. Boot the image.
. Run the following commands to tell the device what server URL to connect to:
+
[source,sh,subs="attributes"]
----
unzip credentials.zip autoprov.url
scp -P 2222 autoprov.url root@localhost:/var/sota/import/gateway.url
----
+
[NOTE]
====
You might remember that `credentials.zip` contains a provisioning key shared-credential provisioning. In this case we just need the `autoprov.url` file inside `credentials.zip`. This file contains the URL of your device gateway which is specific to your account.
====
. Copy the device credentials and device gateway root CA certificate to the device.
+
[source,sh]
----
export device_dir=path/to/device/dir
scp -P 2222 -pr ${device_dir} root@localhost:/var/sota/import
----
+
[NOTE]
====
Replace `path/to/device/dir` with the device directory that you noted when  xref:generatetest-devicecert.adoc[generating the device certificate].
====
+
. _(Optional)_ When the copy operation has completed, ssh into your device and check the aktualizr log output with the following `systemd` command:
+
`journalctl -f -u aktualizr`
+
Once the certificates have copied, the following chain of events should occur:
+
.. The server authenticates the client device by verifying that the client's certificate was signed by the root CA private key that was uploaded in step 2.
.. The client device authenticates the server by verifying that the server's certificate was signed by the server's internal root CA private key.
.. The device is provisioned and appears online in the web UI.


==  Enable and install _with_ an HSM

As described in the xref:index.adoc[introduction], it's a good idea to use a Hardware Security Model (HSM) to hold potentially sensitive device credentials.

The following procedure describes how to use QEMU and link:https://www.opendnssec.org/softhsm/[SoftHSM] to simulate a device with an HSM.

However, the procedure for your HSM will probably be different. We've provided these instructions as a basic guide to how this provisioning method works but you'll need to make further changes on your own. For example, you'll probably need to adapt your BSP so that aktualizr can access the keys from your HSM.

To enable device-credential provisioning and install device certificates _with_ an HSM, follow these steps: ::

. Add the following lines to your `conf/local.conf`:
+
----
SOTA_CLIENT_FEATURES = "hsm"
SOTA_CLIENT_PROV = "aktualizr-device-prov-hsm"
SOTA_DEPLOY_CREDENTIALS = "0"
IMAGE_INSTALL_append = " softhsm-testtoken dropbear "
----
+
[NOTE]
====
The line `IMAGE_INSTALL_append = " softhsm-testtoken dropbear "` ensures that softhsm and an ssh server are installed on the image. You'll need to ssh into the device to copy the certificates to the hsm.
====
. Build a standard image using bitbake.
. Boot the image.
. Run the following commands to tell the device what server URL to connect to:
+
[source,sh,subs="attributes"]
----
unzip credentials.zip autoprov.url
scp -P 2222 autoprov.url root@localhost:/var/sota/import/gateway.url
----
+
[NOTE]
====
You might remember that `credentials.zip` contains a provisioning key shared-credential provisioning. In this case we just need the `autoprov.url` file inside `credentials.zip`. This file contains the URL of your device gateway which is specific to your account.
====
. Copy the device credentials and device gateway root CA certificate to the device's HSM.
+
[source,sh]
----
export device_dir=path/to/device/dir
scp -P 2222 -pr ${device_dir} root@localhost:/var/sota/import
----
+
[NOTE]
====
Replace `path/to/device/dir` with the device directory that you noted when  xref:generatetest-devicecert.adoc[generating the device certificate].

For the QEMU simulated HSM, replace `path/to/device/dir` with the credentials directory of the relevant device.
====
+
. _(Optional)_ When the copy operation has completed, ssh into your device and check the aktualizr log output with the following `systemd` command:
+
`journalctl -f -u aktualizr`
+
Once the certificates have copied, the following chain of events should occur:
+
.. The server authenticates the client device by verifying that the client's certificate was signed by the root CA private key that was uploaded in step 2.
.. The client device authenticates the server by verifying that the server's certificate was signed by the server's internal root CA private key.
.. The device is provisioned and appears online in the web UI.
