= Moving from evaluation to production
ifdef::env-github[]

[NOTE]
====
We recommend that you link:https://docs.ota.here.com/ota-client/latest/{docname}.html[view this article in our documentation portal]. Not all of our articles render correctly in GitHub.
====
endif::[]


The procedures to deploy OTA Connect in a realistic production scenario are a little more complex than the basic xref:getstarted::index.adoc[Get Started] procedures. However, you don't need to commit the resources for a full production roll-out right at the beginning of the process.

That's why it's better to work in phases when setting up OTA Connect in your organization. We recommend that you work in three main phases:

. __Evaluate OTA Connect__
. __Integrate OTA Connect__
. __Deploy your OTA-enabled solution__

No matter which phase you're in, there are 4 basic tasks you'll need to do:

. Build device images with an aktualizr-based client on it.
. Sign and upload the device images.
. Provision devices with authentication credentials for your account.
. Send updated images to some or all of your devices.

This guide contains chapters to guide you through each phase. The sections below give you an introduction to the phased approach.

== Evaluate OTA Connect

During the evaluation phase, you should focus on testing the basic update functionality to make sure that you understand how it works. At this stage, you don't need to think about customization or production-level security. You'll use basic, minimal device images for test boards, or even just simulate devices, and OTA Connect will handle the software signing on the server. For provisioning, you'll use a shared registration key for all your devices.

=== Recommendations

Here are our recommendations for xref:intro-evaluate.adoc[evaluating OTA connect]:

include::partial$recommended-steps.adoc[tags=evaluate-steps]

== Integrate OTA Connect

In this phase, you'll move more towards a realistic production workflow. This will take you into some more complex tasks, like generating unique device keys for registering devices, signed with your own certificate authority. You also might start thinking about using libaktualizr to customize your update flow--for example, to integrate with a user interface, or to update Secondary ECUs. You'll also take your software signing keys offline, and sign software yourself before uploading it.

=== Recommendations

Here are our recommendations for xref:intro-prep.adoc[integrating OTA Connect into your production workflows]:

include::partial$recommended-steps.adoc[tags=integrate-steps]

== Deploy a fully production-ready OTA solution

You've done your testing and now you're ready to xref:intro-prod.adoc[use OTA Connect in production]. You need to make sure that your device provisioning process is production-ready and that your software is available in your production account.


=== Recommendations

Here are our recommendations for deploying OTA Connect to production:

include::partial$recommended-steps.adoc[tags=deploy-steps]
