= garage-sign
ifdef::env-github[]

[NOTE]
====
We recommend that you link:https://docs.ota.here.com/ota-client/latest/{docname}.html[view this article in our documentation portal]. Not all of our articles render correctly in GitHub.
====
endif::[]

xref:https://github.com/advancedtelematic/ota-tuf/tree/master/cli[garage-sign] is a tool for managing your OTA Connect software repository and securely signing software versions. It allows you to directly change, sign, and upload your xref:uptane.adoc[Uptane] metadata.

.Why use `garage-sign`
****
`garage-sign` is useful in OTA Connect for managing the keys for signing your software. If your software image is not an OSTree image, you would need `garage-sign` to upload your xref:uptane.adoc[Uptane] metadata.

Before using `garage-sign`, it is important to be familiar with the following two concepts.

* *Offline keys*
+
In a production environment, we recommend that you keep the keys for signing software versions offline. Therefore, the OTA Connect server will no longer sign software for you, instead, they will be signed locally by your machine. This maintains the security of the software because if someone gained access to your OTA Connect account, they will be able to send malicious software to your devices. However, if your keys are offline, your devices will not recognize the software as it will not have the correct credentials. This is where `garage-sign` becomes useful. For non-OSTree images, the `garage-sign` tool is used to manage and rotate your keys offline as well as sign your software.


* *Local repository*
+
A repository is a location for storing software packages. A local repository is a server that exists on your local machine such as your computer. When using the `garage-sign` tool, it is important to create a local repository on your machine that contains your credentials from OTA Connect, and your keys for signing metadata. With your keys existing locally on your machine, any changes you make to them will not directly affect your devices on OTA Connect. It also ensures the security of your keys during production.

****


== Prerequisites of `garage-sign`

. Download the latest version of the `garage-sign` tool from link:https://tuf-cli-releases.ota.here.com/index.html[here].
. Unzip the file you have downloaded to a location on your computer.
. Change the directory of your terminal on the command line to that location.
. Afterwards, open the `garage-sign` folder in your terminal. You can also print the help command to view the list of all possible commands with this tool.
+
[source,bash]
----
cd garage-sign/
bin/garage-sign --help
----

For more information, please refer to the link:https://github.com/advancedtelematic/ota-tuf/tree/master/cli[`garage-sign` README file].


== Use of `garage-sign` with OTA Connect

To use the `garage-sign` tool with OTA Connect, you need to perform the following steps:

. Initialize a new image repository locally on your computer that pulls your `credentials.zip` from OTA Connect.
+
[source, bash]
----
garage-sign init \
  --repo <reponame> \ <1>
  --credentials </path/to/credentials.zip> <2>
----
+
<1> The name of your image repository which is to be initialized by the `init` command is provided here.
<2> Here you provide the path of your `credentials.zip` file downloaded from your account on the https://connect.ota.here.com[OTA Connect Portal].

. Ensure you have the latest `targets.json` file by pulling it from OTA Connect.
+
[source, bash]
----
garage-sign targets pull --repo <reponame>
----

The above commands create a local repository in a directory called `/tuf/<reponame>`. This directory will contain your `credentials.zip` file and has a tree structure as shown below:

[source, bash]
----
tuf/<reponame>
├── config.json
├── credentials.zip
├── keys
│   ├── targets.pub <1>
│   └── targets.sec <2>
└── roles
    ├── root.json   <3>
    ├── targets.json.checksum
    └── unsigned
        └── targets.json <4>
----

<1> The public part of your `targets` key
<2> The private part of your `targets` key
<3> The `root.json` metadata file
<4> The `targets.json` metadata file


== Use cases of `garage-sign` with OTA Connect

In most use cases, more than one `garage-sign` command is used to perform a specific task. A few use cases will be discussed in this section, however the use of the `garage-sign` tool is not limited to these.

=== Generate new keys

You might generate new keys if you:

* xref:rotating-signing-keys.adoc#_rotate_the_online_keys_with_your_new_offline_keys[want to rotate your online keys with your new offline keys].
* believe your keys have been compromised.
* would like to revoke the current keys for signing metadata.

==== Workflow to generate new keys

When generating new keys for metadata, you perform the following steps:

. First, generate the new `root` and `targets` keys by running the command `garage-sign key generate` twice.
+
[source,bash]
----
garage-sign key generate \
  --repo <reponame> \
  --name myroot \ <1>
  --type <ed25519|rsa> <2>
garage-sign key generate \
  --repo <reponame> \
  --name mytargets \
  --type <ed25519|rsa>
----
+
<1> You can give any name to the keys you generate, which helps to easily identify between the new `root` and `targets` keys. Here, the keys generated are given the names `myroot` and `mytargets`.
<2> The key type must be specified as either Ed25519 or RSA. In OTA Connect, an RSA key is used for signing uptane metadata.

. Afterwards, pull the latest `targets.json` file from OTA Connect with the command `garage-sign targets pull`.
+
[source,bash]
----
garage-sign targets pull --repo <reponame>
----

. Next, use the command `garage-sign move-offline`. This command deletes the old `root` key from OTA Connect, downloads and signs the new `root` key with the newly generated keys, and pushes the new `root.json` file to OTA Connect.
+
[source,bash]
----
garage-sign move-offline \
  --repo <reponame> \
  --old-root-alias originroot \ <1>
  --new-root myroot \ <2>
  --new-targets mytargets <3>
----
+
<1> This is an example of an alias given to the old `root` key. It gets saved with this name.
<2> This is an example of the name given to your new `root` key which you previously generated using the command `garage-sign key generate`.
<3> This is an example of the name given to your new `targets` key which you previously generated using the command `garage-sign key generate`.

. As a final step, sign the new `targets.json` with your newly generated `targets` key and upload it to OTA Connect.
+
[source,bash]
----
garage-sign targets sign --repo <reponame> --key-name mytargets
garage-sign targets push --repo <reponame>
----

Please refer to xref:rotating-signing-keys.adoc#_rotate_the_keys_for_root_and_targets_metadata[rotating the keys for `root` and `targets` metadata] for additional information on generating new keys.

=== Add a new software version

`garage-sign` can also be used to add software packages to your repository with the command `garage-sign targets add`. The packages are downloaded by aktualizr, however `garage-sign` doesn't upload the software file. The `garage-sign targets add` commmand puts new metadata in place, hence you need to tell aktualizr where the software package can be found. This is done by uploading the file somewhere else and providing `garage-sign` with the URL of where it's available.

To add a software version, perform the following steps:

. First upload the software package you wish to add via a URL.
. Next, give the URL where the software was uploaded to the command `garage-sign targets add`. This tells aktualizr where it should download the software file.
+
[source,bash]
----
garage-sign targets add \
  --repo <reponame> \
  --format binary \ <1>
  --length <length-of-package> \ <2>
  --name <packagename> \ <3>
  --version <version> \ <4>
  --sha256 $(sha256sum "${file}" |cut -d' ' -f-1) \ <5>
  --hardwareids <hardware-id1> \ <6>
  --url <url-of-software> <7>
----
+
<1> You must specify the format of the target image to be added--either as an ostree or binary image. In OTA Connect, the `garage-sign` tool is often used to upload `binary` images.
<2> The length of the image to be added must be specified in bytes.
<3> The name of the image you want to upload is specified here.
<4> You must also specify the version number of the target image.
<5> The sha256 hash of the software image is specified here.
<6> This refers to the ids of hardware that your image file supports. An example can be seen in the `targets.json` file xref:customise-targets-metadata.adoc#_anatomy_of_targets_json_metadata[here] under the `custom` field.
<7> The URL of the software package is specified here for `garage-sign` so that aktualizr will know where to find the software file to download.

. Afterwards, sign your `targets.json`, which now contains your new software package, with your `targets` key and upload it to OTA Connect.
+
[source,bash]
----
garage-sign targets sign --repo <reponame> --key-name mytargets
garage-sign targets push --repo <reponame>
----

=== Define metadata expiry

You can also define an expiry date for your metadata using `garage-sign` on the command line. You can do this in two ways--either specifying a fixed date and time or a specific period of time. However, only one type of expiry argument must be used to define the metadata expiry date.

include::ota-client::page$metadata-expiry.adoc[tags=metadata-expiry]

=== Upload a large binary file

The `garage-sign` tool can also be used to upload large binary files up to 3 GB. To upload a large binary file to OTA Connect, perform the following steps:

. Ensure you have the latest version of the `targets.json` file from OTA Connect by pulling the latest version to your local repository.
+
[source,bash]
----
garage-sign targets pull \
  --repo <reponame> <1>
----

. Next, upload the large binary file you want with the command below. This uploads the binary file directly to https://tuf-cli-releases.ota.here.com/index.html[garage-sign on the s3 reposerver].
+
[source,bash]
----
garage-sign targets upload \
  --repo <reponame> \
  --input bigfile.bin </path/to/bigfile.bin>\ <1>
  --name <name-of-target> \
  --version <target-version> <2>
----
+
<1> The path to the file you want to upload is specified here.
<2> The `name` and `version` of your `targets.json` file are specified here. These can be seen in the `targets.json` file under the `custom` field as shown in the example xref:customise-targets-metadata.adoc#_anatomy_of_targets_json_metadata[here].

. After the upload is successful, add the file to your `targets.json`.
+
[source,bash]
----
garage-sign targets add-uploaded \
  --repo <reponame> \
  --input </path/to/bigfile.bin> \
  --name <name-of-target> \
  --version <target-version> \
  --hardwareids <hardware-id1>,<hardware-id2> <1>
----
+
<1> This refers to the ids of hardware that your binary file supports. An example can be seen in the `targets.json` file xref:customise-targets-metadata.adoc#_anatomy_of_targets_json_metadata[here] under the `custom` field.

. Sign the new `targets.json` file with your `targets` key.
+
[source,bash]
----
garage-sign targets sign \
  --repo <reponame> \
  --key-name mytargets
----

. Finally, push the new `targets.json` file to OTA Connect.
+
[source,bash]
----
garage-sign targets push \
  --repo <reponame>
----
