= Integrate OTA Connect
ifdef::env-github[]

[NOTE]
====
We recommend that you link:https://docs.ota.here.com/ota-client/latest/{docname}.html[view this article in our documentation portal]. Not all of our articles render correctly in GitHub.
====
endif::[]


Once you've evaluated the basic functions of OTA Connect, you're ready to integrate OTA Connect into your real-world workflows. This might include building your own OTA client based on libaktualizr, separating out different software repositories for different environments, and more.

You will also start thinking about production-ready security, making sure that your device provisioning and software signing processes reflect what you want to use in production. You also want to set up the software repository for your development account.

Here are our recommended steps for integration:

* xref:add-environments.adoc[*Set up different environments*]
+
Avoid mixing up test software and production software by uploading the software under different environments.

* xref:libaktualizr-why-use.adoc[*Integrate libaktualizr with the client software on your board*]
+
When you move to production, you'll probably want to integrate OTA functionality into your board's native software rather than using the default stand-alone client.

* xref:build-ota-enabled-images.adoc[*Build and deploy your integration*]
+
Once have a working version of your integration, you'll want to build a disk image that contains it. You can then flash this image to other test devices.

* xref:cross-deploy-images.adoc[*Transfer disk images to a QA repository*]
+
After you've built your images, you'll want to hand them over to your QA team, who are ideally testing the software in a QA environment with its own software repository.

* xref:device-cred-prov-steps.adoc[*Set up provisioning with device credentials*]
+
Install device certificates yourself rather than having the OTA Connect server install them automatically. This also allows you to set your own device IDs.

* xref:secure-software-updates.adoc[*Secure your software repository*]
+
To secure your software updates, all files are accompanied by metadata that is signed with several private keys. You need to move the most important private keys from the server and take them offline.

