= Integrate libaktualizr into your solution
ifdef::env-github[]

[NOTE]
====
We recommend that you link:https://docs.ota.here.com/ota-client/latest/{docname}.html[view this article in our documentation portal]. Not all of our articles render correctly in GitHub.
====
endif::[]


////
This topic is supposed to outline the main use cases the product aims to address. The body of the guide must show how to use the product to implement these use cases.

For libaktualizr We already have this topic: https://docs.atsgarage.com/client-config/advanced-update-control-with-libaktualizr.html
The following text was taken from the linked topic and is a proposal for the introcdution to the integration guide.

Feel free to adapt it or leave as-is.
////

The OTA Connect client (aktualizr) is designed to be run as a standalone component on an embedded system and can manage the entire software update process. However, most automotive production use cases will have requirements that go beyond what the standalone client can provide. For example, some in-vehicle interfaces are proprietary and under NDA, so their implementation must be kept separate from aktualizr.

== Why use libaktualizr?

You can integrate the OTA update functionality yourself and minimize the involvement of external consultants. For this purpose, you can use libaktualizr to build your own OTA update solution.

Typical scenarios for making your own client could be:

* You want to integrate OTA Connect functionality with a third-party HMI
* You want to integrate OTA Connect with a third-party interface that installs software on Secondary ECUs
* You want to constrain network traffic and software updates to specific vehicle states
* You want to provide motorists or service staff with progress indicators for specific software updates.

To get started, have a look at our https://github.com/advancedtelematic/libaktualizr-demo[demo app] in GitHub or read through our guide to xref:libaktualizr-getstarted.adoc[getting started with libaktualizr].
