= Manage metadata expiry dates
ifdef::env-github[]

[NOTE]
====
We recommend that you link:https://docs.ota.here.com/ota-client/latest/{docname}.html[view this article in our documentation portal]. Not all of our articles render correctly in GitHub.
====
endif::[]

If you xref:rotating-signing-keys.adoc[take the keys for signing metadata offline], you need to refresh the metadata expiry date before it is reached. Otherwise, you won't be able to push updates. You can also define your own expiry dates when you take your keys offline.

The default expiry dates are as follows:

* For `targets.json`, the expiry date is **31 days** from the last time you ceated or modified metadata.
* For `root.json`, the expiry date is **365 days** from the last time you ceated or modified metadata.

== Define your own expiry dates

Depending on how you use OTA Connect, set the expiry dates in one of the following ways:

* If you build software images using Yocto and our `meta-updater` layer, update your *build configuration*.
* If you use the standalone command-line tools, add extra *command-line arguments*.


[{tabs}]
====
Build configuration::
+
--
include::partial$config-descriptions.adoc[tags=buildconfig-hint]

.Build configuration parameters for metadata expiry
[cols="2a,3a",options="header"]
|====================
|Configuration  | Description
|
`GARAGE_TARGET_EXPIRES` 
| 
include::partial$config-descriptions.adoc[tags=metadata-expires]
----
GARAGE_TARGET_EXPIRES = "2018-01-01T00:01:00Z"
----

|
`GARAGE_TARGET_EXPIRE_AFTER`
| 
include::partial$config-descriptions.adoc[tags=metadata-expireafter]
----
GARAGE_TARGET_EXPIRE_AFTER = "1Y3M5D"
----

|====================



--

Command-line arguments::
+
--
If you use the `garage-sign` command to take your keys offline, you can also sign your metadata with one of the following expiry arguments.

For more information, see the `garage-sign` xref:garage-sign-reference.adoc[reference] documentation.

.Command-line arguments for metadata expiry
[cols="2a,4a",options="header"]
|====================
|Configuration  | Description
|
`--expires`
| 
include::partial$config-descriptions.adoc[tags=metadata-expires]

[source, bash]
----
garage-sign targets sign --expires 2018-01-01T00:01:00Z  --repo myimagerepo --key-name mytargets
----

|
`--expire-after`
| 
include::partial$config-descriptions.adoc[tags=metadata-expireafter]

[source, bash]
----
garage-sign targets sign ----expire-after 1Y3M5D  --repo myimagerepo --key-name mytargets
----
|====================

--
====
