= Register your test root certificate
ifdef::env-github[]

[NOTE]
====
We recommend that you link:https://docs.ota.here.com/ota-client/latest/{docname}.html[view this article in our documentation portal]. Not all of our articles render correctly in GitHub.
====
endif::[]


//MC: This is a copy of the topic "provide-root-cert.adoc" but intended for the "test" use case. Need to use more includes to reduce redundancy

Once you have a root certificate, you need to have it registered with your account so that the OTA Connect server can verify your device certificates.

* To register your test root certificate with HERE OTA Connect, send it to link:mailto:otaconnect.support@here.com[otaconnect.support@here.com].

If you followed our recommendations, you should have one OTA Connect account for testing and another for production. Make sure that you specify that this certificate is for your *test* account.

* While you wait for confirmation from the OTA Connect support team, you can already  xref:generatetest-devicecert.adoc[generate a test device certificate].

* Once you've received confirmation that the root certificate has been registered, you can xref:enable-device-cred-provtest.adoc[enable device-credential provisioning and install the certificate] on a test device.