:toc: macro
:toc-title:

= Release process

To create a new link:https://github.com/advancedtelematic/aktualizr/releases[release of aktualizr and garage-deploy], there are several discrete steps to follow:

toc::[]

== Update the changelog and other docs

This is normally a good time to update the link:../../../../../CHANGELOG.md[changelog]. Ideally, the changelog should be updated with the new release number before creating the release so that the packaged source code includes the correct information about the release. The easiest way to check the changelog is to review all PRs merged to master since the last release was made and to verify that any important changes that impact the user experience are reflected in the changelog.

There are a few additional documents that should be updated to refer to the new release:

* The link:../../../../README.adoc#reference-documentation[docs README] contains a table with links to the doxygen docs for each release.
* The link:install-garage-sign-deploy.adoc[garage-deploy] installation guide contains a reference to the latest release of the garage-deploy Debian package.

== Create a new tag

Releases are built automatically by gitlab from annotated tags of the form `major.minor`, where `major` and `minor` are numbers. We normally set `major` to the current year and `minor` to an incrementing number beginning at 1.

To create a release, checkout the revision you want to bless, then:

----
git tag -as <tag>   # e.g. git tag -a 2018.4
git push github <tag>
----

Gitlab will build this tag and automatically create a release for it on github.

== Update doxygen on github

To update the doxygen documentation for master on github, you will need to do something like the following:

1. In an aktualizr repo, run `make doxygen` (or `make docs`) in the build directory.
1. Clone a second aktualizr repo and run `git checkout gh-pages`.
1. In the second repo, run `git rm search/* *.css *.html *.js *.png *.map *.md5 *.png *.svg`.
1. Copy the contents of `<build_dir>/docs/doxygen/html` into the root of the second repo. (Something like `cp -a <build_dir>/docs/doxygen/html/* <second_repo>`.)
1. In the second repo, run `git add .`, `git commit -as`, and `git push`.
1. Wait a minute or two for github to refresh and render the files.

== Add doxygen pages for the new release on github

To add doxygen docs for a new tag, you will need to do something like the following:

1. Check out the tag or commit you wish to add (`git checkout 2018.63`, for example).
1. Clean out the build directory (to remove stale objects), then run CMake and doxygen again:
+
----
rm -rf build/*
cd build
cmake ..
make doxygen
----
+
1. Clone a second aktualizr repo and run `git checkout gh-pages`.
1. In the second repo, make a directory for the tag or commit you wish to add, i.e. `mkdir 2018.63`.
1. Copy the contents of `<build_dir>/docs/doxygen/html` into the directory you just created. (Something like `cp -a <build_dir>/docs/doxygen/html/* <second_repo>/2018.63`.)
1. In the second repo, run `git add 2018.63`, `git commit -as`, and `git push`.
1. Wait a minute or two for github to refresh and render the files.

== Update the description of the github release

Once the release is ready on github, it should be edited to include a link to the changelog and doxygen documentation for that particular release. You can use a previous release as a model of how to format these links.

== Update the Uptane fork of aktualizr

Uptane has a fork of aktualizr in link:https://github.com/uptane/aktualizr[their namespace]. It should be updated with the same version of aktualizr used to make the new release.

== Update the homebrew recipe for aktualizr

Homebrew should be updated with the same version of aktualizr used to make the new release.

== Test the released Debian packages

Don't forget to test the resulting Debian packages manually!
