= Test software update security
ifdef::env-github[]

[NOTE]
====
We recommend that you link:https://docs.ota.here.com/ota-client/latest/{docname}.html[view this article in our documentation portal]. Not all of our articles render correctly in GitHub.
====
endif::[]


//MC: This is a copy of the topic "secure-software-updates.adoc" but intended for the "test" use case. Need to use more includes to reduce redundancy.

To secure your software updates, OTA Connect ensures that all software files have accompanying metadata that is signed according to the Uptane framework.

When evaluating OTA Connect you don't have to worry about signing this metadata yourself. The OTA Connect server automatically signs the metadata after you upload software.

However, for this process to work, the OTA Connect server must host the xref:pki.adoc[private keys] that are used to sign the metadata. This is a security risk -- if an attacker is able to infiltrate the OTA Connect server, they can use these private keys to sign metadata for malicious software and send it to your devices.

To prevent an event like this from happening, you should take these private keys offline and sign the metadata in your development environment. Then you can push the signed metadata back to the server. To do this, you use the `garage-sign` command which is part of our xref:install-garage-sign-deploy.adoc[`garage-deploy`] tool.
