= Simulate a device without building a disk image
:page-partial:
ifdef::env-github[]

[NOTE]
====
We recommend that you link:https://docs.ota.here.com/ota-client/latest/{docname}.html[view this article in our documentation portal]. Not all of our articles render correctly in GitHub.
====
endif::[]


:page-layout: page
:page-categories: [quickstarts]
:page-date: 2018-11-19 11:28:47
:page-order: 5
:icons: font
include::partial$aktualizr-version.adoc[]
:sectnums:

You can try out OTA Connect without having to build a whole device image. This can be useful for testing the system outside of actual device updates. In this guide, you will install aktualizr (the OTA client software) on your local machine, create a directory with configuration files and credentials for aktualizr to use, and run aktualizr from there.

== Prerequisites

* A Linux or MacOS machine to run aktualizr on
* xref:ota-client::generating-provisioning-credentials.adoc[Provisioning credentials] (`credentials.zip` file)

== Install aktualizr locally

The first step is to install an aktualizr binary on your system. You can install packages for MacOS (with https://brew.sh[homebrew]), Ubuntu 16.04, or Ubuntu 18.04. If you use a different system, you will need to build from source.

[{tabs}]
====
Ubuntu 16.04 package::
+
--
.Download the release from GitHub
[source,sh,subs="attributes"]
----
wget https://github.com/advancedtelematic/aktualizr/releases/download/{aktualizr-version}/aktualizr-ubuntu_16.04.deb
----

.Install the downloaded .deb
[source,sh,subs="attributes"]
----
sudo apt install ./aktualizr-ubuntu_16.04.deb
----

.Disable the aktualizr system service
[source,sh,subs="attributes"]
----
sudo systemctl stop aktualizr.service
sudo systemctl disable aktualizr.service
----
--

Ubuntu 18.04 package::
+
--
.Download the release from GitHub
[source,sh,role="secondary",subs="attributes"]
----
wget https://github.com/advancedtelematic/aktualizr/releases/download/{aktualizr-version}/aktualizr-ubuntu_18.04.deb
----
.Install the downloaded .deb
[source,sh,subs="attributes"]
----
sudo apt install ./aktualizr-ubuntu_18.04.deb
----
.Disable the aktualizr system service
[source,sh,subs="attributes"]
----
sudo systemctl stop aktualizr.service
sudo systemctl disable aktualizr.service
----
--

MacOS (homebrew)::
+
--
[source,sh,role="secondary"]
----
brew tap advancedtelematic/otaconnect
brew install aktualizr
----
--

Build from source::
+
--
.Install the prerequisites
Modify as needed for your distro. See https://github.com/advancedtelematic/aktualizr for further instructions
[source,sh,subs="attributes"]
----
sudo apt install asn1c build-essential clang clang-format-6.0 clang-tidy-6.0 \
cmake curl doxygen graphviz lcov libarchive-dev libboost-dev \
libboost-filesystem-dev libboost-log-dev libboost-program-options-dev \
libcurl4-openssl-dev libostree-dev libp11-3 libp11-dev libpthread-stubs0-dev \
libsodium-dev libsqlite3-dev libssl-dev python3-dev python3-openssl \
python3-venv sqlite3 valgrind
----
.Clone the sources from GitHub
[source,sh,subs="attributes"]
----
git clone --recursive -b {aktualizr-version} https://github.com/advancedtelematic/aktualizr
cd aktualizr
----
.Build and install
[source,sh,subs="attributes"]
----
mkdir build
cd build
cmake ..
make install
----
--
====

== Prepare an environment for a simulated device

Make a directory for each device that you want to simulate. This directory will store your configuration files for that device, plus the device metadata and keys.

Each directory should contain the following:

* credentials.zip
* sota_local.toml -- a config file for aktualizr
* (Optional) A `virtualsec.json` file containing the configuration for one or more secondary ECUs.footnote:[The terms "primary" and "secondary" ECU are used in the Uptane specification. For more information about the difference between primary and secondary ECUs, see our overview of the xref:ota-client::uptane.adoc#_primary_and_secondary_ecus[Uptane framework\].]

An example directory is below:

[{tabs}]
====
Directory structure::
+
[source,role="primary"]
----
localtest/
├── credentials.zip
├── virtualsec.json
└── sota_local.toml
----
sota_local.toml::
+
[source,role="secondary"]
----
include::example$sota-local.toml[]
----
virtualsec.json::
+
[source,role="secondary"]
----
include::example$virtualsec.json[]
----
====

[NOTE]
====
Aktualizr’s config file format changed with version 2019.5, released July 12, 2019. These instructions apply only to version 2019.5 and later.
====

== Run aktualizr in the prepared directory

From the directory you've created, run aktualizr and point it to the current directory for its configuration:

    aktualizr -c .

This will start aktualizr in its normal mode: it will provision with the server using the `credentials.zip` provided, then start listening for updates. You can also xref:ota-client::aktualizr-runningmodes-finegrained-commandline-control.adoc[selectively trigger aktualizr] or use any of the other options; you just need to specify `-c .` each time.

You should now be able to see your simulated device provisioned into your OTA Connect account, with two secondary ECUs listed.

NOTE: Because the aktualizr config we've given uses relative paths, you *must* run aktualizr from the directory you created. However, if you prefer, you can use absolute paths in the config file instead. The reason we've chosen to use relative paths is to make it easy to simulate multiple distinct devices, by simply making a copy of the whole directory.
