= Supported boards
ifdef::env-github[]

[NOTE]
====
We recommend that you link:https://docs.ota.here.com/ota-client/latest/{docname}.html[view this article in our documentation portal]. Not all of our articles render correctly in GitHub.
====
endif::[]


* https://github.com/advancedtelematic/meta-updater-raspberrypi[Raspberry Pi 2, 3, and 4] (4 beginning with warrior)
* https://github.com/advancedtelematic/meta-updater-minnowboard[Intel Minnowboard]
* https://github.com/advancedtelematic/meta-updater-qemux86-64[Native QEMU emulation]
* Renesas R-Car H3 and M3
* https://github.com/advancedtelematic/meta-updater-ti/[TI BeagleBone Black] (rocko only, using TI SDK 05.03)
* https://github.com/advancedtelematic/meta-updater-ti/[TI AM65x industrial development kit] (rocko only, using TI SDK 05.03)

Additionally, there is community support for https://github.com/ricardosalveti/meta-updater-riscv[RISC-V] boards, in particular the Freedom U540.

We also historically supported the https://github.com/advancedtelematic/meta-updater-porter[Renesas Porter] board.

== Adding support for your board

If your board isn't supported yet, you can add board integration code yourself. To do this, follow our xref:bsp-integration.adoc[BSP integration guide].


If you want our developers to add support for your board, contact us at mailto:otaconnect.support@here.com[] and we can discuss a potential NRE (Non-recurring Engineering) agreement.

[NOTE]
====
Although we have focused on U-Boot and GRUB so far, other bootloaders can be configured to work with OSTree as well. If you want to use a different bootloader, contact us at mailto:otaconnect.support@here.com[].
====

Your images will also need network connectivity to be able to reach an actual OTA backend. Our `poky-sota` distribution does not mandate or install a default network manager but our supported platforms use the `virtual/network-configuration` recipe, which can be used as a starting example.

== Minimum hardware requirements for controllers (ECUs)

The aktualizr binary is a lightweight {cpp} application between 2-5 MB in size. It uses around 20 MB RAM, although some of that comes from shared libraries. It uses a minimum amount of other resources when idle.

The following hardware is required for your Primary ECU:

* At a minimum, the board or device aktualizr is running on will need **64 MB of RAM** and **128 MB of storage**.
* We recommend using a board with slightly higher specs, however. **256 MB of RAM** and **512 MB storage** are reasonable targets, especially if you plan to process large, complex software updates. The aktualizr process itself won't consume significantly more RAM with larger updates, but the filesystem cache memory usage might increase.

[NOTE]
====
If you plan to send updates to low-performance Secondary ECUs, you can also use a more minimal implementaton called link:https://github.com/advancedtelematic/uptiny[`libuptiny`]. This utility is only 10 KB and performs a minimal verification of software metadata that is less resource intensive. For more information on `libuptiny`, contact us at mailto:otaconnect.support@here.com[].
====
