= Troubleshooting BSP Integration
ifdef::env-github[]

[NOTE]
====
We recommend that you link:https://docs.ota.here.com/ota-client/latest/{docname}.html[view this article in our documentation portal]. Not all of our articles render correctly in GitHub.
====
endif::[]

include::partial$aktualizr-version.adoc[]

== U-Boot loading the wrong config file

U-Boot finds its initial configuration file by looping through the partitions in order and searching for `uEnv.txt` first in `/`, then in `/boot/`. If U-Boot isn’t loading the correct initial file, you should check the partitions layout, and see if there’s a vendor-provided `uEnv.txt` in a partition that comes physically before the one you’ve placed the OSTree initial `uEnv.txt`.


== Vendor's environment setup script overrides values that meta-updater has set.

Values specified in `local.conf` have the highest priority in a Yocto build. Most vendors provide a setup script for the build environment that also generates a `local.conf` with many values pre-populated. In some cases, those values can conflict with changes that the meta-updater makes.


For the LS1043ARDB, the environment setup script added a line to the `local.conf` that overrode the `INITRAMFS_IMAGE` value. To fix this, you need to specify the correct value in your `local.conf` when you build:
[source,bash]
----
INITRAMFS_IMAGE = "initramfs-ostree-image"
----

== Further Information

Building an integration with a new board involves dealing with several different systems. See the following links for more information on this:

* https://www.yoctoproject.org/docs/{yocto-version}/mega-manual/mega-manual.html[Yocto Mega Manual, v{yocto-version}]: The Yocto Mega Manual is a concatenation of all the various other reference manuals; it’s usually better to use the individual manuals if you know what you’re looking for. In particular, these three are the most frequently used in the BSP development domain:
** https://www.yoctoproject.org/docs/{yocto-version}/ref-manual/ref-manual.html[Yocto Reference Manual, v{yocto-version}]
** https://www.yoctoproject.org/docs/{yocto-version}/bsp-guide/bsp-guide.html[Yocto BSP Developer's Guide, v{yocto-version}]
** https://www.yoctoproject.org/docs/{yocto-version}/bitbake-user-manual/bitbake-user-manual.html[Bitbake User Manual, v{yocto-version}]

* https://ostreedev.github.io/ostree/[libostree reference documentation]
** https://ostreedev.github.io/ostree/deployment/[Deployments]
** https://ostreedev.github.io/ostree/atomic-upgrades/[Atomic Upgrades]

* https://www.denx.de/wiki/DULG/Manual[U-Boot reference documentation]
** https://www.denx.de/wiki/view/DULG/UBootCommandLineInterface[CLI]
** https://www.denx.de/wiki/view/DULG/UBootScripts[Scripting]
