= Recommended client configuration
ifdef::env-github[]

[NOTE]
====
We recommend that you link:https://docs.ota.here.com/ota-client/latest/{docname}.html[view this article in our documentation portal]. Not all of our articles render correctly in GitHub.
====
endif::[]


Before you start developing or deploying to production, you should check that your configuration file has appropriate settings for your use case.

For more details about the full client configuration settings, see the xref:aktualizr-config-options.adoc[client configuration reference].

== Recommended settings for development

[cols="1,1,1a",options="header,footer"]
|====================
|Name  | Default | Description
|`polling_sec`  | `10` |
Interval between polls (in seconds).

The default polling internal designed to make it convenient for you test and develop OTA update functions.
|`force_install_completion`  | `true` |
Forces installation completion. Causes a system reboot in case of an ostree package manager. Emulates a reboot in case of a fake package manager.

You'll want to set this to `true` when developing because it's more convenient.

|====================

== Recommended settings for production

[cols="1,1,1a",options="header,footer"]
|====================
|Name  | Default | Description
|`polling_sec`  | `86400` | When moving to production you'll want to have a much longer interval.
In fact, for production, we don't support intervals less the 1 hour (3,600 seconds). Longer internals help you to reduce the internet bandwidth and power consumption for your devices.

We recommend an internal between 1 and 7 days (86,400 to 604,800 seconds).
|`force_install_completion`  | `false`  |
If you followed our recommendation to enable automatic rebooting for development, you should turn it off again for production.
|====================


