= OTA Connect security: The Uptane framework
ifdef::env-github[]

[NOTE]
====
We recommend that you link:https://docs.ota.here.com/ota-client/latest/{docname}.html[view this article in our documentation portal]. Not all of our articles render correctly in GitHub.
====
endif::[]

:page-layout: page
:page-categories: [concepts]
:page-date: 2018-01-10 13:55:45
:page-order: 80
:icons: font
:toc: macro


HERE OTA Connect aligns with the https://uptane.github.io[Uptane] security framework. Uptane was developed in response to the clear need for a comprehensive security model for automotive updates, and is the first security system that provides serious compromise resilience in that spacefootnote:["Uptane is the first compromise-resilient software update security system for the automotive industry.", https://uptane.github.io].

== Uptane structure

The most important concept in Uptane is that there are two sets of metadata, from separate sources, that must agree with each other and have valid cryptographic signatures.

// The {zwsp} in the following line is a zero-width space, and it's there as
// a workaround to make the footnote behave correctly.

The first comes from the *image Repository*{zwsp}footnote:[This image repository is based on https://theupdateframework.com/[TUF (The Update Framework)].]. The image repository contains metadata for update packages that are _valid_ install targets, and its metadata is signed by a chain of trust with offline keys.

The second comes from the *Director*, which controls what updates (selected from the valid install targets) should actually be installed on devices. The Director uses online keys, and is part of the OTA Connect service.

== Uptane metadata

The Uptane specification defines several different types of metadata, but the two main files that you need to manage are as follows:

* `root.json`:
+
This file contains information about all the roles that can sign software metadata.
+
To see an example of this metadata, open the link:https://raw.githubusercontent.com/theupdateframework/tuf/develop/tests/repository_data/repository/metadata/root.json[sample `root.json` file] from the TUF (The Update Framework) website.

* `targets.json`:
+
The instance of `targets.json` in your image repository contains information about all the valid software files.
+
As mentioned previously, there are two versions of each metadata file, one in your image repository and one in the Director service.
+
The _other_ instance of `targets.json` is in the Director service. It only contains information about the software files that are included in a specific update. The entries in this file are cross-referenced with the corresponding entries in `targets.json` for your image repository.
+
Basically this comparison is answering the question:
+
"__Can I be sure that the files in this update really come from my offical software repository?__".
+
To see an example of this metadata, open the link:https://raw.githubusercontent.com/theupdateframework/tuf/develop/tests/repository_data/repository/metadata/targets.json[sample `targets.json` file] from the TUF (The Update Framework) website.

== Signing updates of system images

OTA Connect manages the Director for you. When you create an update campaign, we update the Director behind the scenes, signing the metadata for each image-device tuple in the campaign.

The keys for the metadata in your image repository should be managed on your side; we provide tooling to help you do just that. When you build a new device, bitbake automatically signs the image for you, using keys that you specify in the build's `local.conf`{zwsp}footnote:[These keys are packed inside the zip file specified by the `SOTA_PACKED_CREDENTIALS` line.]. Your initial key is created by HERE OTA Connect, delivered to you inside your `credentials.zip` file, and kept online for convenience and bootstrapping; for any production use you should xref:rotating-signing-keys.adoc[manage the keys for software metadata] yourself and store them securely offlinefootnote:[Proceed with caution! Once you take the key offline, HERE Technologies cannot recover it.].

== Primary and Secondary ECUs

In the Uptane framework, an ECU is categorized as either a Primary or a Secondary ECU. In most cases, a vehicle has one Primary ECU and several Secondary ECUs. The Primary ECU is responsible for downloading and distributing software to the Secondary ECUs. In many cases, the Telematics Control Unit (TCU) serves the role of Primary ECU. A Primary ECU also verifies and distributes the Uptane-compliant metadata associated with each piece of software.

Secondary ECUs, such as the Transmission or Body control modules, receive the software and should also perform some form of metadata verification. If the ECU has sufficient processing capabilities, it should perform a full verification of the Uptane-compliant metadata, otherwise it should at least perform a partial verification.

To get an overview of the ECUs detected in a device, open the OTA Connect web application and navigate to the device details for the device. This view shows the ECUs grouped according to whether they are Primary and Secondary ECUs.
