= Configure your own device IDs
ifdef::env-github[]

[NOTE]
====
We recommend that you link:https://docs.ota.here.com/ota-client/latest/{docname}.html[view this article in our documentation portal]. Not all of our articles render correctly in GitHub.
====
endif::[]


In OTA Connect, a device has two types of identifier: an internal device UUID, and a standard device ID.

// MC: use xref:otaconnect-identifiers.adoc[identifier]: when topic is finished
By default, OTA Connect generates a random device ID for you, but you can override this behavior.

The standard way to specify device identity is in the device certificate -- specifically, in the Subject Distinguished Name (DN) field.

This method requires that you use device-credential provisioning which tells OTA Connect to use your device certificates for authentication. This method is a little more complicated than the "shared-credential" provisioning method that you might have used in the "Get Started" guide.

However you can try our test procedures to specify your own Device IDs. Earlier in this guide, we showed you how to xref:generate-devicecert.adoc[generate and sign a device certificate] using a self-signed root certificate.

* You can define your own device ID in the device certificate, by changing step 1 of that procedure

** Replace the existing sample command:
+
`export device_id=${DEVICE_ID:-$\{DEVICE_UUID}}`
+
Update the command with your device ID instead:
+
`export device_id=<your-id>`
+
For example:
`export device_id=1HTHCATR81H391382`

** You can then continue the test procedure to provision your device.

* If you already have your own procedure for generating device certificates, then you're probably already using your own device IDs to bind each certificate to the device.

In any case, OTA Connect uses the device ID that you've defined in your device certificates instead of automatically generating one.
