#ifndef AKTUALIZR_OPENSSL_COMPAT_H
#define AKTUALIZR_OPENSSL_COMPAT_H

#include <openssl/opensslv.h>

#ifndef OPENSSL_VERSION_NUMBER
#error "OPENSSL_VERSION_NUMBER is not defined"
#endif

#define AKTUALIZR_OPENSSL_PRE_11 (OPENSSL_VERSION_NUMBER < 0x10100000)

#define AKTUALIZR_OPENSSL_AFTER_11 (!AKTUALIZR_OPENSSL_PRE_11)

#endif  // AKTUALIZR_OPENSSL_COMPAT_H
