#!/bin/bash

if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
    deb-systemd-helper unmask 'aktualizr.service' >/dev/null || true
    deb-systemd-helper update-state 'aktualizr.service' >/dev/null || true
fi

