#!/bin/bash

shell_pid=$(ps -o ppid=  -p $PPID)
shell_pid=${shell_pid#" "}

initiator_pid="$(ps -o ppid=  -p $shell_pid)"
initiator_pid=${initiator_pid#" "}

initiator_cmdline="$(tr -d '\0' < "/proc/$initiator_pid/cmdline")"

# touch a file if aktualizr was installed by itself
if [[ "$initiator_cmdline" = /usr/bin/aktualizr* ]]; then
    touch "/tmp/aktualizr_reboot_flag"
fi
