FROM ubuntu:xenial
LABEL Description="Ubuntu Xenial package testing dockerfile"

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && apt-get -y install debian-archive-keyring
RUN apt-get update && apt-get install -y --no-install-suggests --no-install-recommends \
  libarchive13 \
  libc6 \
  libcurl3 \
  libglib2.0-0 \
  libsodium18 \
  libsqlite3-0 \
  libssl1.0.0 \
  libstdc++6 \
  lshw \
  openjdk-8-jre \
  python3 \
  zip

RUN apt install -y software-properties-common
RUN add-apt-repository ppa:mhier/libboost-latest
RUN apt update
RUN apt install -y libboost1.67

ADD ./scripts /scripts
