/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.dbus 3.1.5.v201601121430.
* Used org.franca.core 0.9.1.201412191134.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#include "SotaClientDBusDeployment.hpp"

namespace v1 {
namespace org {
namespace genivi {
namespace swm {
namespace SotaClient_ {

// Type-specific deployments

// Attribute-specific deployments

// Argument-specific deployments

// Broadcast-specific deployments
 
} // namespace SotaClient_
} // namespace swm
} // namespace genivi
} // namespace org
} // namespace v1
