[provision]
provision_path = "credentials.zip"
primary_ecu_hardware_id = "local-fake"

[uptane]
secondary_configs_dir = "secondary_configs"

[logger]
loglevel = 1

[storage]
path = "storage"

[pacman]
type = "none"
