== Installing aktualizr via debian package

Aktualizr makes .deb packages available via the https://github.com/advancedtelematic/aktualizr/releases[GitHub releases page]. Download and install the .deb package, for example:

----
sudo apt install ./aktualizr.deb
----

=== Setting up aktualizr

The debian package will install, enable, and start an `aktualizr` systemd service immediately after it's installed. However, there are some configuration steps that should be taken before the service starts. To use aktualizr with a server (i.e. https://github.com/advancedtelematic/ota-community-edition/[OTA Community Edition] or https://docs.atsgarage.com[HERE OTA Connect]), you will need to download the provisioning credentials file provided by the server and place it at `/var/sota/sota_provisioning_credentials.zip`.

Additionally, if you wish to pass extra command line arguments to aktualizr, you can do so by creating `/usr/lib/sota/sota.env` to set the `AKTUALIZR_SECONDARY_CONFIG` environment variable. For example, to set up the log level to debug:

----
AKTUALIZR_SECONDARY_CONFIG="--loglevel 0"
----

You can pass any other command line arguments in this file, as well.

For security reasons, we recommend creating the `/usr/lib/sota/sota.env` file even if you aren't going to use it. The file should be owned by root, with `600` permissions.

=== Secondary ECUs

The debian package ships with a default secondary ECU configured. This acts like a dummy device, dropping whatever file you send it into `/tmp/demo-virtual-secondary/firmware.bin`. If you want to override this default, you'll need to create `/usr/lib/sota/sota.env` and override `AKTUALIZR_SECONDARY_CONFIG` with a blank string, like so:

----
AKTUALIZR_SECONDARY_CONFIG=""
----

=== Building the debian package

After following the main build setup steps, just `make package` instead of `make` to create a debian package from your current branch, for example:

----
git clone --recursive https://github.com/advancedtelematic/aktualizr
cd aktualizr
mkdir build
cd build
cmake  -DCMAKE_BUILD_TYPE=Debug -DBUILD_DEB=ON ..
make package
----

=== Making a Release on github

Releases are built automatically by Travis from annotated tags of the form `major.minor`, where `major` and `minor` are numbers.  To create a release, checkout the revision you want to bless, then:

----
git tag -a <tag>   # e.g. git tag -a 2018.4
git push ats <tag>
----

Travis will build this tag and automatically release it to github.  Don't forget to test the resulting Debian package manually!
