== Installing aktualizr via debian package

Aktualizr makes .deb packages available via the https://github.com/advancedtelematic/aktualizr/releases[GitHub releases page]. Download and install the .deb package, for example:

----
sudo apt install ./aktualizr.deb
----

=== Setting up aktualizr

The debian package will install, enable, and start an `aktualizr` systemd service immediately after it's installed. However, there are some configuration steps that should be taken before the service starts. To use aktualizr with a server (i.e. https://github.com/advancedtelematic/ota-community-edition/[OTA Community Edition] or https://docs.atsgarage.com[HERE OTA Connect]), you will need to download the provisioning credentials file provided by the server and place it at `/var/sota/sota_provisioning_credentials.zip`.

You can pass any other command line arguments in this file, as well.

For security reasons, we recommend creating the `/usr/lib/sota/sota.env` file even if you aren't going to use it. The file should be owned by root, with `600` permissions.

=== Secondary ECUs

The debian package ships with a default secondary ECU configured. This acts like a dummy device, dropping whatever file you send it into `/tmp/demo-virtual-secondary/firmware.bin`.

=== Building the debian package

After following the main build setup steps, just `make package` instead of `make` to create a debian package from your current branch, for example:

----
git clone --recursive https://github.com/advancedtelematic/aktualizr
cd aktualizr
mkdir build
cd build
cmake  -DCMAKE_BUILD_TYPE=Debug -DBUILD_DEB=ON ..
make package
----

=== Making a Release on github

Releases are built automatically by Travis from annotated tags of the form `major.minor`, where `major` and `minor` are numbers. We normally set `major` to the current year and `minor` to an incrementing number beginning at 1.

To create a release, checkout the revision you want to bless, then:

----
git tag -as <tag>   # e.g. git tag -a 2018.4
git push ats <tag>
----

Travis will build this tag and automatically create a release for it on github. This is normally a good time to update the link:../CHANGELOG.md[changelog] and the doxygen documentation. Ideally, the changelog should be updated with the new release number before creating the release so that the packaged source code includes the correct information about the release. The process for updating the doxygen is specified in the link:README.adoc#developer-documentation[docs README].

Don't forget to test the resulting Debian packages manually!
