= Running aktualizr with fault injection

To test the system in adverse conditions, it can be useful to make aktualizr fail in a controlled fashion.

link:https://blitiri.com.ar/p/libfiu/[libfiu] provides a framework to do that, and aktualizr supports a number of controllable fail points.

== Setup

libfiu needs to be installed on the target machine. For local compilation on a Debian-derived system, the distribution package can be used:

    apt install fiu-utils libfiu-dev

Fault injection must then be enabled at CMake configure time with the `-DFAULT_INJECTION=on` option (refer to general building instructions for more details).

`fiu-run` and `fiu-ctrl` can now be used on the newly compiled aktualizr binary to inject faults (refer to corresponding man pages).

For example, when using the fake package manager:

    fiu-run -c 'enable name=fake_package_install' aktualizr -c . once

== List of fail points

Please try to keep this list up-to-date when inserting/removing fail points.

- `fake_package_install`: make the fake package manager installation to fail with a generic error code

== Use in unit tests

It is encouraged to use fail points to help unit testing sad paths. Tests that require fault injection should only be run if the `FIU_ENABLE` macro is defined.
