= Integrating Aktualizr into other software

Aktualizr is designed to be run as a standalone component on an embedded system and can manage the entire software update process. This is suitable for simple cases, but falls short in more complex environments. For example:

- User consent for updates
- Interactive feedback of installation progress

Some of these are not always necessary. Many users today are satisfied with applications (Google Docs/GMail, Office 365, Chrome) that automatically update without user interaction. For these products the designer takes on the responsibility of making updates seamless, both in terms of zero downtime for the user and that there are no significant regressions. That is not always the case, and aktualizr is designed to also work in constrained environments where updates may make a vehicle undrivable for an extended period of time.

== Functional Requirements

1. Integration with 3rd party HMI
2. Integration with 3rd party interfaces to install software on secondary ECUs
3. Limit network traffic and installation to specific vehicle states
4. Progress bars

== Non-functional Requirements

1. Since in-vehicle interfaces are often proprietary and under NDA, the implementation must be kept separate from the Aktualizr tree.
2. It should be possible to have the integration performed by a separate team
3. New projects often have unexpected requirements, so flexibility is important.

== Overview

Aktualizr can be incorporated into other applications by checking out the aktualizr source repository and referencing it via `add_subdirectory` in the parent project's `CMakeLists.txt`.

When used as a library, Aktualizr should be seen as a toolkit of useful parts that are handy when building an Uptane-based software update system. As such there is not a strict definition of a 'stable' part of the API, and we will modify the API to improve it over time.  Internally, we will use CI to detect these API breakages and simultaneously patch the downstream projects.  We can also do that same to external open source consumers of the API.  This follows the model of OpenBSD and Google, where we prefer to fix the software rather than to accumulate backwards compatibility hacks.  Downstream consumers should update the Aktualizr version regularly, to ensure any required changes are small.

Beyond API compatibility, there is also no guarantee of ABI compatibility between versions (even patch revisions).  In the future we may provide a subset of the API behind a PIMPL wrapper that will be API and ABI stable.

== Why not IPC?

It would be possible to allow other components to interface with Aktualizr via a IPC interface such as D-Bus or Sockets. This would have the some advantages, such as:

 - Process Isolation
 - Easier to assemble pieces together and hack together things with scripts.
 - Easier privilege separation

However we believe the disadvantages outweigh them:

- Have to build an IPC mechanism
- Have to build bridges to connect this 'common' IPC mechanism to whatever the end-user system has picked
- New features may require simultaneous changes to the aktualizr IPC these bridges.
- Hard to replace built-in functionality with external functionality (e.g. Package Managers)
- Harder to add steps to the high-level workflow.

It is still possible to write a wrapper that would expose libaktualizr via an IPC mechanism, but this can be written with a specific use-case and IPC technology in mind.

== Why not a C API

We tried to design a C language API that would have a stable API/ABI, and would be easy to call from other languages. However this was rejected for the following reasons:

* The bridge would require quite a lot of code
* The most likely consumer of the API would be a C++ application, where C idioms like manual reference counting would need to be converted back to RAII holders.
* The potential consumers of this API all wanted to use it in 'unusual' ways, for example changing the PackageManager implementation. This would mean that we would have to allow lots of these parts to be plugable, and we'd need to wrap the APIs that we already have and introduce some kind of plugable interface. This isn't impossible, but it results in code that is unnecessary in the approach where we expose the C++ classes directly.
* Committing to a stable ABI will introduce extra maintenance costs, even in cases where we are making changes that don't affect any consumers.



