= Legacy secondary support

The Uptane specification indicates that secondary ECUs, i.e. ECUs that don't have direct access to the global network and can only get updates from the primary ECUs, should also be able to verify Uptane metadata and sign version manifests. In this way, secondaries are protected not only from compromise of the remote server, but also from compromise of the primary ECU or in-vehicle network.

However, in some cases it might be necessary to be able to update legacy secondaries via the Uptane primary without modifying the secondaries' flashing procedure. Such secondaries still take full advantage of Uptane's protection against remote server/global network compromise and can also implement some in-ECU protection with proprietary mechanisms.

In the latter case, the primary (i.e. aktualizr) will take care of verifying metadata and signing version manifests on behalf of secondaries by using an external utility for ECU discovery and flashing.

== Flasher command line interface

The command line interface shall support three commands.

=== api-version

  $ example-flasher api-version

Returns a single line with the version number of the API that the tool supports. At present, there is only one version, so this should always return `1`. This command should always succeed.

=== list-ecus

  $ example-flasher list-ecus

Returns a list of the ECUs that are attached to the system. Each line starts with the hardware identifier, and may optionally include the serial number as the second column. For example:

  <hardware-id[0]> <ecu-serial[0]>
  <hardware-id[1]> <ecu-serial[1]>
  <hardware-id[2]>
  ...

Hardware IDs are used by Uptane to check if a firmware image is suitable for the particular device, so the hardware ID specified for your image in https://www.atsgarage.com/[ATS Garage] should exactly match what is returned by the flasher.

The ECU serial uniquely identifies an ECU in the Uptane repository, so it should be unique globally, not just within the vehicle scope. If a serial is not provided for an entry, a unique serial is generated randomly by the primary for that entry.

Hardware IDs for ECUs without provided serials should be unique within the scope of the list. Each entry is treated as a single ECU by Uptane. If you want to flash multiple ECUs of the same kind and maintain atomicity of the update, it is the responsibility of the flasher to verify that all the ECUs either get the new image or continue to run the old image if the update fails.

The command shall fail if the ECUs could not be found due to communication error or if the discovered number of ECUs does not match the expected value. On subsequent runs, the command should output the same number of ECUs. If some ECUs stop responding, these can be skipped. ECU hotplugging is not supported.

=== install-software

  $ example-flasher install-software --hardware-identifier <hw-id> [--ecu-identifier ecu-serial] --firmware /path/to/firmware.img

Delivers an update to a particular ECU. `--ecu-identifier` should be provided for any ECU that was listed with a serial by the `list-ecus` command. If `list-ecus` did not provide a serial for a given ECU, `--ecu-identifier` may be skipped for that ECU, and the flasher should ignore it if it is provided.

The command's return value should indicate the result of the installation:

[options=header]
|===================
| Return value | Meaning
| 0 | Installation completed successfully.
| 1 | The firmware image is invalid.
| 2 | Installation failure. The previous firmware was not modified.
| 3 | Installation failure. The previous firmware was partially overwritten or erased.
|===================

=== Additional options

All three commands should support one additional option to control the log level:

  $ example-flasher <command> --log-level N

Valid values for `N` are `0..4`:

[options=header]
|===================
| Log level | Meaning
| 0 | Trace
| 1 | Debug
| 2 | Informational
| 3 | Warning
| 4 | Error
|===================

The flasher may ignore this option.

== Integration with aktualizr

The aktualizr update client has a `--legacy-interface /path/to/example-flasher` command line option which will make all the ECUs reported by the `list-ecus` command available to the aktualizr and https://www.atsgarage.com/[ATS Garage].

In most cases you will want to build your Uptane-enabled system using the https://github.com/advancedtelematic/meta-updater[meta-updater] Yocto layer. Please read the documentation listed in the README for general information about building with meta-updater. Adding support for legacy secondaries requires two more things to do:

  . Create a recipe that will install your flasher at some location in the device's file system. For more information on how to write a recipe, please consult the http://www.yoctoproject.org/docs/current/dev-manual/dev-manual.html#new-recipe-writing-a-new-recipe[Yocto documentation].
  . In your local.conf set `SOTA_LEGACY_SECONDARY_INTERFACE = "<path>"`, where the path is the absolute path to the flasher as seen from the booted device.

Make sure that you're using a version of meta-updater that is new enough to support these features. The head of the `pyro` branch supports it at the time of writing.

== Additional requirements for secondaries

As a result of an update, a secondary should run either the new version of firmware (success case) or the one it was running before the update (failure case). The traditional way to implement this requirement is by using a dual-bank memory layout on the secondary.
