
= Linux Secondaries

Aktualizr and meta-updater support updating secondary devices running Linux as well as deeply embedded (RTOS) devices.

There is a demonstration of this using qemu and two images in meta-updater called 'primary-image' and 'secondary-image'. The networking setup works in the following way:

Both the primary and secondary have two network interfaces. The first one (vlan 0 in qemu) is connected to the internet via the 'user mode' networking in qemu (-net user), and is set up to support connecting to the device via ssh. 

The second network interface is used for the internal network between the devices. The primary provides a DHCP server, and the clients run DHCP clients.

== To make it go

Add `SOTA_CLIENT_FEATURES = "secondary-network"` to local.conf. This will configure the primary to search for secondary devices.  Note that only automatic provisioning is supported at the moment.

Build the primary and secondary images with `bitbake primary-image secondary-image`.

Start the secondary image first with:

     ../meta-updater/scripts/run-qemu-ota --no-gui --machine qemux86-64 --secondary-network secondary-image

The `--secondary-network` option enables a second virtual network interface.

Then start the primary:

     ../meta-updater/scripts/run-qemu-ota --no-gui --machine qemux86-64 --secondary-network primary-image

Starting aktualizr on the primary will take some time, because of a IPv6 bug in systemd.

== When things go wrong

To retry provisioning, stop aktualizr and aktualizr-secondary then delete `/var/sota/sql.db` on the primary and `/var/sota/secondary.db` on the secondary.
