
= Linux Secondaries

Aktualizr and meta-updater support updating secondary devices running Linux as well as deeply embedded (RTOS) devices.

There is a demonstration of this using qemu and two images in meta-updater called 'primary-image' and 'secondary-image'. The networking setup works in the following way:

Both the primary and secondary have two network interfaces. The first one (vlan 0 in qemu) is connected to the internet via the 'user mode' networking in qemu (-net user), and is set up to support connecting to the device via ssh. 

The second network interface is used for the internal network between the devices. The primary provides a DHCP server, and the clients run DHCP clients.

== To make it go

Add `SOTA_CLIENT_FEATURES = "secondary-network"` to local.conf. This will configure the primary to search for secondary devices.  Note that only automatic provisioning is supported at the moment.

Build the primary and secondary images with `bitbake primary-image secondary-image`.

First start the secondary image with:

     ../meta-updater/scripts/run-qemu-ota --no-gui --machine qemux86-64 --secondary-network secondary-image

The `--secondary-network` option enables a second virtual network interface.

Once the secondary is booted, start the primary:

     ../meta-updater/scripts/run-qemu-ota --no-gui --machine qemux86-64 --secondary-network primary-image

Starting aktualizr on the primary will take some time, because of a (suspected) IPv6 bug in systemd.

To check that it is working, run `aktualizr-info` on the primary, and a secondary ECU should be present:

    root@qemux86-64:~# aktualizr-info
    Storage backend: Sqlite
    Device ID: smooth-kuerbissuppe-526
    Primary ecu serial ID: 5552578ec14089cbcc9e6c40e6eb1b88a0618726c44af901bbe5ce7aa3c51f79
    Primary ecu hardware ID: qemux86-64
    Secondaries:
    1) serial ID: 856ea8f3c07bb62813a5352a2005f361d7c1018639367d203cd26c2a06e38af2
    hardware ID: qemux86-64
    Provisioned on server: yes
    Fetched metadata: yes

== When things go wrong

To retry provisioning, stop aktualizr and aktualizr-secondary then delete `/var/sota/sql.db` on the primary and `/var/sota/secondary.db` on the secondary.
