= Primary/Secondary Protocol

This protocol describes the communication between the primary and exactly one secondary.

For simplicity, messages are written in JSON. This will not be the case in the actual
implementation.

== Steps

The Primary sends a `PrimaryHello` message to initiate the protocol.

The Secondary responds with a `SecondaryHello` message.

The primary sends a `ProtocolBegin` message.

The protocol then loops according to the parameters defined in the `SecondaryHello` message.

Either party may abort the protocol at any time with a `Terminate` message.

Apart from the initial triple handshake, messages are sent async without acknowledgements. 

Before a secondary attempts to install, it should send a `Terminate` message since in all
likelihood an installation will cause a restart.

TODO: Secondaries should be able to send a report back to the primary without the primary having to
initiate the protocol. Should there be `PrimaryHello` -> `SecondaryAck` and `SecondaryHello` ->
`PrimaryAck` pairs of handshakes?

=== Messages

All messages are contained in a envelope that identifies the message type.

```
{
  "type": "TYPE",
  "message": ...
}
```

=== `PrimaryHello`

```
{
  "protocol-versions": [VERSION_0, VERSION_1, ...],
}
```

=== `SecondaryHello`

```
{
  "protocol-version": PROTOCOL_VERSION,
  "timeserver-nonce": "NONCE", # optional
  "verification": "FULL|PARTIAL",
  "message-streaming-method": "METHOD",
  "manifest": {...} # signed manifest
}
```

=== `ProtocolBegin`

```
{
  "nonce": {...} # nonce + sig, optional
}
```

=== TUF/Uptane Metadata

```
{
  "repo": "DIRECTOR|IMAGE",
  "name": "{root,timestamp,targets,...}.json",
  "metadata": {...}
}
```

=== Image

```
{
  "name": "IMAGE_NAME",
  "size": SIZE
}
```

followed by the binary image.

=== `Terminate` 

```
{
  "code": CODE,
  "message": "MESSAGE"
}
```

The code will and messages are primarily used for logging, but the code may be used to determine if
the primary attempts to reinitiate the protocol.

== Message Streaming Methods

=== Partial Verification Double Push

- director root loop
  - X.root.json
  - X.root.json
  - increment and continue loop until latest sent
- director targets loop
  - targets.json
  - targets.json
- image
  - loop if multiple images (probably not?)

=== Secondary Pull 

The secondary sends messages requesting metadata, and the primary proxies those requests to the
server and optionally serves these messages from a cache.

Request message:

```
{
  "repo": "DIRECTOR|IMAGE",
  "name": "{root,timestamp,targets,...}.json"
}
```

or

```
{
  "image-name": "NAME"
}
```

The primary will validate that the image is permitted to be sent to the secondary before sending it.
