= OTA Connect Developer Guide

This directory contains the source of our **OTA Connect Developer Guide** which is published to our https://docs.ota.here.com[documentation portal].

You can also read the source files for this guide. To read this guide locally or in GitHub, start with the xref:ota-client-guide/modules/ROOT/nav.adoc[table of contents].

[NOTE]
====
Content includes, such as code snippets or reused text snippets will not render correctly in Github.
====

== Reference documentation

Additional documentation intended for developers that may need to use the libaktualizr API should refer to link:https://advancedtelematic.github.io/aktualizr/index.html[this doc]:
[NOTE]
====
The link above is for the doxygen docs on master. Doxygen docs for the following tagged release versions are also available:

* https://advancedtelematic.github.io/aktualizr/2018.8/index.html[2018.8]
* https://advancedtelematic.github.io/aktualizr/2018.9/index.html[2018.9]
* https://advancedtelematic.github.io/aktualizr/2018.11/index.html[2018.11]
* https://advancedtelematic.github.io/aktualizr/2018.12/index.html[2018.12]
* https://advancedtelematic.github.io/aktualizr/2018.13/index.html[2018.13]
* https://advancedtelematic.github.io/aktualizr/2019.1/index.html[2019.1]
* https://advancedtelematic.github.io/aktualizr/2019.2/index.html[2019.2]
* https://advancedtelematic.github.io/aktualizr/2019.3/index.html[2019.3]
* https://advancedtelematic.github.io/aktualizr/2019.4/index.html[2019.4]
* https://advancedtelematic.github.io/aktualizr/2019.5/index.html[2019.5]
* https://advancedtelematic.github.io/aktualizr/2019.6/index.html[2019.6]
====

=== Updating doxygen on github

To update the doxygen documentation for master on github, you will need to do something like the following:

1. In an aktualizr repo, run `make doxygen` (or `make docs`) in the build directory.
1. Clone a second aktualizr repo and run `git checkout gh-pages`.
1. In the second repo, run `git rm search/* *.css *.html *.js *.png *.map *.md5 *.png *.svg`.
1. Copy the contents of `<build_dir>/docs/html` into the root of the second repo. (Something like `cp -a <build_dir>/docs/html/* <second_repo>`.)
1. In the second repo, run `git add .`, `git commit -as`, and `git push`.
1. Wait a minute or two for github to refresh and render the files.

==== Adding docs for a new tag

To add doxygen docs for a new tag, you will need to do something like the following:

1. Check out the tag or commit you wish to add (`git checkout 2018.63`, for example).
1. Clean out the build directory (to remove stale objects), then run CMake and doxygen again:
+
----
rm -rf build/*
cd build
cmake ..
make doxygen
----
+
1. Clone a second aktualizr repo and run `git checkout gh-pages`.
1. In the second repo, make a directory for the tag or commit you wish to add, i.e. `mkdir 2018.63`.
1. Copy the contents of `<build_dir>/docs/html` into the directory you just created. (Something like `cp -a <build_dir>/docs/html/* <second_repo>/2018.63`.)
1. In the second repo, run `git add 2018.63`, `git commit -as`, and `git push`.
1. Wait a minute or two for github to refresh and render the files.
