= Security


Aktualizr uses the UPTANE security framework, which assumes a powerful adversary which can:

* Monitor and modify all network traffic
* Compromise the master update server (and all https keys)
* Compromise some of the other keys in the system

There are several assumptions about the platform that need to be met by the platform Aktualizr is integrated in to produce a secure system.


== Assumption: DNS eventually resolves correctly

An attacker who can poison the DNS cache of the local system can stop the system receiving updates until the DNS entry times out.

Controlling DNS can only deny service: it does not allow the attacker to control the system in any way.

The deployment should ensure that the DNS TTL is short enough, or deploy a secure system for name resolution such as DNSSEC.

== Assumption: Time is trusted

The local time of the system is used to check the validity of signatures. An attacker who can modify the local time of the system can cause signatures to either become invalid (denying service) or can allow an expired signature to be used. The default NTP implementation on many embedded systems is not secure against an attacker with control over the network, and so a secure source of time should be used.  This might be a network time service (such as Google's https://roughtime.googlesource.com/roughtime[Roughtime]) or a local RTC.
