= TUF / UPTANE

== Background

https://uptane.github.io[UPTANE] is a framework for securing updates to vehicles.

Support for UPTANE will be added in stages, starting with basic support for parsing the root.json/snapshot.json/targets.json/timestamp.json files and the ability to fetch update descriptions via the 'director' that runs in rvi_sota_server.


== Using the TUF endpoint (PRO-2538)

In this phase we will use the new API endpoint to fetch the update (instead of /api/v1/mydevice/:uuid/updates).  We won't be performing any of the checks in TUF/UPTANE that defend against compromised servers at this stage.

This will be a new type of client interface alongside SotaHttpClient and SotaRVIClient.

Note that this endpoint requires using mutual TLS authentication.

The `feat/pro-2539/tuf` branch of rvi_sota_client is a useful reference for the behaviour of this endpoint.

== Validating Sample JSON

The tests/tuf/sample1 directory contains a sample set of signed metadata.  We should implement compatible signatures validation for those. Note that the signatures are calculated over the 'Canonical JSON' representation of the signed part: https://tools.ietf.org/html/draft-staykov-hu-json-canonical-form-00


== Config Changes

TODO
